# Generated by Django 5.1.1 on 2024-10-19 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdb', '0002_alter_enrollment_enrollment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='studentdb.department'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='instructor_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instructors', to='studentdb.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='studentdb.department'),
        ),
    ]
